version: '3'
services:
  myredis_demo :
    image: "redis:latest"
    ports:
    - "6379:6379"
    container_name: myredis_demo
    volumes:
    - /docker/redis/data:/redis/data
  mysql_demo:
    image: "mysql:latest"
    ports:
    - "3306:3306"
    container_name: mysql_demo
    security_opt: 
    - seccomp:unconfined
    environment:
       MYSQL_ROOT_PASSWORD: 123456
       MYSQL_DATABASE : HttpReports
    volumes:
    - /docker/mysql/data:/var/lib/mysql
     # - /docker/mysql/conf:/etc/mysql/conf.d
  mycoreweb:
    image: myweb:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: mycoreweb
    environment:
    #- ASPNETCORE_ENVIRONMENT=Production
    - ASPNETCORE_URLS=https://+:443;http://+:80
    - ASPNETCORE_HTTPS_PORT=5000
    #- ASPNETCORE_Kestrel__Certificates__Default__Password=123tan
    - ASPNETCORE_Kestrel__Certificates__Default__Path=testCert.pfx
    ports:
    - "5001:80"
    - "5000:443"
    depends_on:
    - myredis_demo
    - mysql_demo
    - mynginx
  mynginx:
    image: "nginx:latest"
    ports:
      - "8080:80"
    restart: always
    container_name: mynginx
    volumes:
    - C:/Users/hal_t/docker/conf/nginx.conf/:/etc/nginx/